public class Test {

    private string name='Ali Can';
    private integer age = 13;
    private boolean successful= true;
    
    public string getName(){
        return name;
    }
    public integer getAge(){
        return age;
    }
    public boolean getSuccesful(){
        return Successful;
     }
    
    public void setName(string name){
       this.name = name; 
    }
    public void setAge(integer age){
        this.age = age;
    }
      public void setSuccessful(boolean successful){
    this.successful = successful;        
    }    
    
    
}